# Generated by Django 3.2.7 on 2021-10-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ('order',), 'verbose_name': 'column', 'verbose_name_plural': 'columns'},
        ),
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.IntegerField(),
        ),
    ]
