# Generated by Django 3.2.7 on 2021-10-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_auto_20211001_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
