# Generated by Django 3.2.7 on 2021-10-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0008_schema_delimiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='delimiter',
            field=models.CharField(default=',', max_length=50),
        ),
    ]
