# Generated by Django 3.2.8 on 2021-10-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0008_schema_delimiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='file_name',
            field=models.CharField(default='file_name', max_length=100),
        ),
    ]
