# Generated by Django 3.2.8 on 2021-10-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0009_schema_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='file_exists',
            field=models.BooleanField(default=False),
        ),
    ]
