# Generated by Django 3.2.7 on 2021-11-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0009_alter_schema_delimiter'),
        ('schemas', '0010_schema_file_exists'),
    ]

    operations = [
    ]
