# Generated by Django 3.2.8 on 2021-10-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0010_schema_file_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='all_column',
            field=models.BooleanField(default=False),
        ),
    ]
