# Generated by Django 3.2.7 on 2021-11-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0011_merge_20211103_1858'),
        ('schemas', '0011_schema_all_column'),
    ]

    operations = [
    ]
